[package]
name = "web_triangle"
version = "0.1.0"
authors = ["Remy"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
[profile.release]
lto = "thin"
[dependencies]



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html