[package]
name = "ria_ch10"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.6.0"
rayon = "1"
crossbeam ="0.7"